### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mcale6** [dina-lab3D/CombFold#2]
Is there the possibility to get the full PAE matrix from an Input Complex e.g crystal structure using the AF2trans function?

**Comment by ben-shor** [comment]
The AF2trans extracts transformations from a PDB model.  So, for example, given a PDB model with two interacting chains and a reference PDB structure for each chain, the output will be the transformation needed to move the reference chains according to the model of the two chains. Therefore, it can't really help you with getting PAE scores. 

Feel free to ask if you have any further questions or need assistance with any other topic.

**Comment by mcale6** [comment]
Isnt the pae matrix calculated with: 
```latex
e_{ij} = k T_{i}^{-1} \circ \mathbf{x}_{j} - T_{\text{true}}_{i}^{-1} \circ \mathbf{x}_{\text{true}}_{j} + k_{i}

So we get T for the model and reference and the actual position we already have?

**Comment by ben-shor** [comment]
I am not sure what you mean exactly. 
When we refer to PAE here, we mean the PAE matrix outputted by AlphaFold, in fact, no code in this repository calculates PAE.

For what exactly do you need the PAE matrix?

**Comment by mcale6** [comment]
Ok than Im not really understanding how the assembled complex from the subunits can be assessed as the PAE will be different after assembling? I read the section where this is described in the paper but I cannot wrap my head around. (Thats why I thought the PAE can be recalculated separately)

**Comment by ben-shor** [comment]
OK, I'll try to clarify.
The PAE calculated by AlphaFold for each model is used to calculate a score for each transformation.
The final confidence score assigned to the assembled complex is a weighted average of the scores of all transformations.

just as a side note - the default code here actually uses i-plddt instead of PAE to simplify the pipeline, but this change should be negligible.

I hope this clears things up, but let me know if you have further questions.
